# Generated by Django 2.0.6 on 2018-06-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0002_auto_20180618_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_by_recommender', to='many_to_many.Person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='many_to_many.Person'),
        ),
    ]
