# Generated by Django 2.0.6 on 2018-06-18 05:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [

        ('foreignkey', '0004_auto_20180618_0247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ForeignKeyUser',
        ),
    ]
